### ISSUE TITLE
sd-gpu error in preprocess

### ISSUE THREAD

**Issue by tcnichol** [awi-response/darts-nextgen#78]
Here is the error:

`xarray.core.merge.MergeError: conflicting values for variable 'spatial_ref' on objects to be combined. You can skip this check by specifying compat='override'.
Could not process folder '/home/toddn/pdg/darts-nextgen/rts_dtaset01/input/planet/PSOrthoTile/1072216/3645114_1072216_2020-08-12_2259'.
Skipping...
conflicting values for variable 'spatial_ref' on objects to be combined. You can skip this check by specifying compat='override'.
Traceback (most recent call last):
  File "/home/toddn/miniconda3/envs/darts-nextgen/lib/python3.11/site-packages/darts/native.py", line 184, in run_native_planet_pipeline
    tile = preprocess_legacy(optical, arcticdem, tcvis, data_masks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toddn/miniconda3/envs/darts-nextgen/lib/python3.11/site-packages/darts_preprocessing/preprocess.py", line 61, in preprocess_legacy
    ds_merged = xr.merge([ds_optical, ds_ndvi, ds_arcticdem, ds_tcvis, ds_data_masks])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toddn/miniconda3/envs/darts-nextgen/lib/python3.11/site-packages/xarray/core/merge.py", line 976, in merge
    merge_result = merge_core(
                   ^^^^^^^^^^^
  File "/home/toddn/miniconda3/envs/darts-nextgen/lib/python3.11/site-packages/xarray/core/merge.py", line 701, in merge_core
    variables, out_indexes = merge_collected(
                             ^^^^^^^^^^^^^^^^
  File "/home/toddn/miniconda3/envs/darts-nextgen/lib/python3.11/site-packages/xarray/core/merge.py", line 290, in merge_collected
    merged_vars[name] = unique_variable(
                        ^^^^^^^^^^^^^^^^
  File "/home/toddn/miniconda3/envs/darts-nextgen/lib/python3.11/site-packages/xarray/core/merge.py", line 144, in unique_variable
    raise MergeError(
xarray.core.merge.MergeError: conflicting values for variable 'spatial_ref' on objects to be combined. You can skip this check by specifying compat='override'.
 `

I'm not sure if this error is something wrong with the various input data I have or something that I need to change. Wasn't sure if doing what this error suggests and adding the compat='override' is a good choice. 

If someone can check, let me know.

**Comment by iona5** [comment]
it seems its trying to merge datasets where some of the source geodata has a different CRS. It shouldn't happen, but i will check over here. I guess its the dataset I sent you?

**Comment by iona5** [comment]
oh, and can you maybe also try it with the **fast** pipeline, so with `run-native-planet-pipeline-fast` ?

**Comment by iona5** [comment]
lets see what the reason for the error actually is. but of course we should remove those at one point.

**Comment by tcnichol** [comment]
I saw the comments here. Let me try to run this again.

**Comment by iona5** [comment]
@tcnichol is this still an issue with the fast pipiline? i guess we wont track issues with the legacy pipeline anymore.
